# Generated by Django 4.2.5 on 2023-09-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('day', models.DateField()),
                ('time', models.TimeField(max_length=5)),
                ('reminder', models.BooleanField(default=False)),
            ],
        ),
    ]
